VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no 
KEY_OVERRIDE_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
MOUSEKEY_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no

VIAL_ENCODERS_ENABLE = no
VIAL_INSECURE = yes

